-- Book-Hub Database Schema (H2 compatible)

-- Books Table
CREATE TABLE IF NOT EXISTS books (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    author VARCHAR(255) NOT NULL,
    category VARCHAR(100) NOT NULL,
    type VARCHAR(50) NOT NULL,
    book_condition VARCHAR(50) NOT NULL,
    cover_url CLOB,
    description VARCHAR(1000),
    price DECIMAL(10, 2),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT idx_category CHECK (category IS NOT NULL),
    CONSTRAINT idx_type CHECK (type IS NOT NULL)
);

-- Users Table
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Sample Data for Books
INSERT INTO books (title, author, category, type, book_condition, cover_url, description, price) VALUES
('Java Programming', 'Herbert Schildt', 'Academic', 'sell', 'Good', '/static/media/java.jpg', 'Comprehensive guide to Java programming', 45.99),
('Clean Code', 'Robert C. Martin', 'Academic', 'rent', 'Like New', '/static/media/cleancode.jpg', 'A handbook of agile software craftsmanship', 29.99),
('Data Structures', 'Mark Allen Weiss', 'Academic', 'sell', 'Good', '/static/media/dsa.jpg', 'Data structures and algorithm analysis in Java', 55.00),
('Spring Boot in Action', 'Craig Walls', 'Academic', 'rent', 'New', '/static/media/springboot.jpg', 'Build modern applications with Spring Boot', 39.99),
('React Explained', 'Zac Gordon', 'Academic', 'sell', 'Like New', '/static/media/react.jpg', 'Modern web development with React', 35.00),
('The Alchemist', 'Paulo Coelho', 'Novel', 'donate', 'Fair', '/static/media/alchemist.jpg', 'A magical fable about following your dreams', NULL),
('Atomic Habits', 'James Clear', 'Motivation', 'sell', 'New', '/static/media/atomichabits.jpg', 'An easy way to build good habits', 25.99),
('Rich Dad Poor Dad', 'Robert Kiyosaki', 'Motivation', 'sell', 'Good', '/static/media/richdad.jpg', 'What the rich teach their kids about money', 19.99),
('It Ends With Us', 'Colleen Hoover', 'Novel', 'rent', 'Like New', '/static/media/itendswithus.jpg', 'A powerful novel about love and courage', 15.99),
('Pride and Prejudice', 'Jane Austen', 'Novel', 'donate', 'Fair', '/static/media/pride.jpg', 'A classic romance novel', NULL);

-- Create a default admin user (password: admin123)
-- Password is BCrypt encrypted version of 'admin123'
INSERT INTO users (name, email, password) VALUES
('Admin User', 'admin@bookhub.com', '$2a$10$8EqY5xN1.VDjKGvh5HqBr.HI1h8qIZN3Q5.YgV8RZXgE7YLKlW8nS');
